reservetion osztály - teremfoglalások
csertant/szikapp pull request #48
Opened 2021-04-18 18:21 UTC by ksolyom

closes #31 
@sarvarimark 
@csertant

2021-04-18 20:06 UTC, csertant commented on lib/business/reservation.dart
> +    await io.deleteReservation(parameter);
Ha itt a 24. sorban eltávolítod a listáról a taskot, akkor a 27. sorban a reservations[taskIndex].uid hibát fog dobni.
Én a lokális listából eltávolítást az IO-s mögé tenném.

2021-04-18 20:54 UTC, csertant requested changes
Nagyon klassz munka, köszi!:)
Egy apróbb igazítást szeretnénk kérni, illetve a filter függvénynél rájöttünk, hogy kissé módosítani kell a specifikációt (ez nem volt benne annó, bocsii) - ha azt még át tudnád formálni pompás lenne.

2021-04-18 20:54 UTC, csertant commented on lib/business/reservation.dart
> +      List<DateTime> startTimes, List<DateTime> endTimes, List<String> rooms) {
A Janitor osztályhoz hasonlóan szuper lenne, ha az egyes feltételekre külön lehetne szűrni.
Említett rész a 49-es sortól: 
https://github.com/csertant/szikapp/blob/36fce33aa5ca60164a9d5065a27df6f57e5ce3c0/lib/business/janitor.dart#L49

Még agyaltunk a kérdésen, és annyi igazítást szerintem jó lenne tennünk, hogy a fix időpont összehasonlítások helyett inkább időintervallum összehasonlítást alkalmazhatnánk. Vagyis adva lenne egyetlen kezdő és egyetlen végső dátum, és amennyiben egy foglalás intervalluma bármilyen kissé is fedi a paraméterekben megadott intervallumot, akkor azt hozzáadja a találatokhoz. Azaz, ha a foglalás start vagy végső időpontja a két időparaméter közé esik, akkor fűzné hozzá.
Az intervallumok összehasonlításához pedig kézre esnek a DateTime beépített [isAfter](https://api.dart.dev/stable/2.12.4/dart-core/DateTime/isAfter.html) és isBefore metódusai.

2021-04-20 20:36 UTC, ksolyom commented on lib/business/reservation.dart
> +      List<DateTime> startTimes, List<DateTime> endTimes, List<String> rooms) {
Ha nem szűrünk kezdő vagy befejező időpontra, akkor a DateTime típusú startTime és endTime paramétereknek mi az értéke?

2021-04-20 22:37 UTC, sarvarimark commented on lib/business/reservation.dart
> +      List<DateTime> startTimes, List<DateTime> endTimes, List<String> rooms) {
Teljesen jogos a kérdés: tanácskozás után arra jutottunk, hogy a startTime, endTime paraméterek nem nullázhatóak; azaz szükségszerűen kap paramétereket a függvény.
Ugyanitt a room parameter viszont nullázható.

2021-04-21 14:14 UTC, sarvarimark approved these changes

2021-04-21 14:32 UTC, csertant approved these changes

2021-04-21 14:36 UTC, merged