Kimaradt fgv megvalóstása
csertant/szikapp pull request #64
Opened 2021-04-29 17:05 UTC by sarvarimark

resolves #49 

Ugyanitt: ez a fajta Edit fgv megvalósítás nekem jobban tetszik, mint az idáigiak, főleg, mert eggyel kevesebb paraméterrel dolgoznánk. Esetleg a többit is ilyen formátumba helyezzem?

2021-04-29 23:06 UTC, csertant requested changes
Szösszenet kommentben.
Egyébként tetszik, térjünk át erre a többi helyen is.

2021-04-29 23:06 UTC, csertant commented on lib/business/reservation.dart
> +    var parameter = {'reservation_id': task.uid};
A paraméter kulcs helyesen csupán 'id'.

2021-04-30 07:46 UTC, sarvarimark commented on lib/business/reservation.dart
> +    var parameter = {'reservation_id': task.uid};
Dokumentáció alapján igen, de mintha a kódban nem. Esetleg erre ránézel?

2021-04-30 09:14 UTC, csertant commented on lib/business/reservation.dart
> +    var parameter = {'reservation_id': task.uid};
Kódban is. Mikor az szerepel, hogy 
```python
self.reqparse.add_argument(
            "id",
            dest="reservation_id",
            type=str,
            help="Reservation id.",
            location="args",
        )
```
az "id" a paraméter neve a külvilág felé, és csak a python script felé "reservation_id"

2021-04-30 09:14 UTC, csertant approved these changes

2021-04-30 09:24 UTC, merged